name: CI (preprod)

on:
  pull_request:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  test-preprod:
    runs-on: ubuntu-latest
    environment: preprod
    env:
      STAGE: preprod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv venv .venv
          uv pip install -e .[dev]
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
      - name: Install ruff
        run: |
          uv pip install ruff
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
      - name: Lint
        run: |
          ruff check .
          ruff format --check .

