name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv venv .venv
          uv pip install -e .[dev]
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
      - name: Run tests
        run: .venv/bin/pytest -q
      - name: Lint
        run: |
          .venv/bin/black --check .
          .venv/bin/isort --check .
